# Netflix Analytics Project

This project analyzes Netflix content trends, ratings, countries, genres, and release patterns using Python, Pandas, and Plotly.

In [1]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

In [2]:
netflix = pd.read_csv("../dataset/netflix_titles.csv")

netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [3]:
netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [4]:
netflix.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [5]:
netflix["type"].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [6]:
fig = px.pie(
    netflix,
    names="type",
    title="Movies vs TV Shows on Netflix"
)

fig.show(renderer="browser")

# Data Cleaning

In [7]:
netflix.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [8]:
netflix = netflix.drop_duplicates()

netflix.shape

(8807, 12)

In [9]:
shape

NameError: name 'shape' is not defined

In [10]:
netflix["country"] = netflix["country"].fillna("Unknown")

In [11]:
netflix["director"] = netflix["director"].fillna("Not Available")

In [12]:
netflix.isnull().sum()

show_id           0
type              0
title             0
director          0
cast            825
country           0
date_added       10
release_year      0
rating            4
duration          3
listed_in         0
description       0
dtype: int64

# Netflix Content Analysis

In [13]:
netflix["rating"].value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [14]:
rating_counts = netflix["rating"].value_counts().head(10)

fig = px.bar(
    x=rating_counts.index,
    y=rating_counts.values,
    title="Top Netflix Ratings"
)

fig.show(renderer="browser")

In [15]:
year_data = netflix["release_year"].value_counts().sort_index()

year_data

release_year
1925       1
1942       2
1943       3
1944       3
1945       4
        ...
2017    1032
2018    1147
2019    1030
2020     953
2021     592
Name: count, Length: 74, dtype: int64

In [16]:
fig = px.line(
    x=year_data.index,
    y=year_data.values,
    title="Netflix Content Growth Over Years"
)

fig.show(renderer="browser")

In [17]:
top_countries = netflix["country"].value_counts().head(10)

top_countries

country
United States     2818
India              972
Unknown            831
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Name: count, dtype: int64

In [18]:
fig = px.bar(
    x=top_countries.index,
    y=top_countries.values,
    title="Top Countries Producing Netflix Content"
)

fig.show(renderer="browser")

In [19]:
netflix["listed_in"].value_counts().head(10)

listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Kids' TV                                            220
Children & Family Movies                            215
Children & Family Movies, Comedies                  201
Documentaries, International Movies                 186
Dramas, International Movies, Romantic Movies       180
Name: count, dtype: int64

In [20]:
top_genres = netflix["listed_in"].value_counts().head(10)

fig = px.bar(
    x=top_genres.index,
    y=top_genres.values,
    title="Top Netflix Genres"
)

fig.show(renderer="browser")

In [21]:
movies = netflix[netflix["type"] == "Movie"]

movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",Unknown,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [22]:
movies.shape

(6131, 12)

In [23]:
movies["duration"].head()

0      90 min
6      91 min
7     125 min
9     104 min
12    127 min
Name: duration, dtype: str

In [24]:
movies["duration"] = movies["duration"].str.replace(" min", "")

In [25]:
movies["duration"] = movies["duration"].astype(float)

In [26]:
movies["duration"].head()

0      90.0
6      91.0
7     125.0
9     104.0
12    127.0
Name: duration, dtype: float64

In [27]:
movies.nlargest(10, "duration")[
    ["title", "duration"]
]

                            title  duration
4253   Black Mirror: Bandersnatch     312.0
717   Headspace: Unwind Your Mind     273.0
2491       The School of Mischief     253.0
2487               No Longer kids     237.0
2484           Lock Your Girls In     233.0
2488              Raya and Sakina     230.0
166   Once Upon a Time in America     229.0
7932                       Sangam     228.0
1019                       Lagaan     224.0
4573                 Jodhaa Akbar     214.0

In [28]:
fig = px.histogram(
    movies,
    x="duration",
    nbins=30,
    title="Netflix Movie Duration Distribution"
)

fig.show(renderer="browser")

In [29]:
movies["duration"].mean()

99.57718668407311

# Key Performance Indicators (KPIs)

In [30]:
total_titles = netflix.shape[0]

total_movies = netflix[netflix["type"] == "Movie"].shape[0]

total_tvshows = netflix[netflix["type"] == "TV Show"].shape[0]

average_movie_duration = movies["duration"].mean()

print("Total Titles:", total_titles)

print("Total Movies:", total_movies)

print("Total TV Shows:", total_tvshows)

print("Average Movie Duration:", average_movie_duration)

Total Titles: 8807
Total Movies: 6131
Total TV Shows: 2676
Average Movie Duration: 99.57718668407311

In [31]:
netflix["director"].value_counts().head(10)

director
Not Available             2634
Rajiv Chilaka               19
Raúl Campos, Jan Suter      18
Suhas Kadav                 16
Marcus Raboy                16
Jay Karas                   14
Cathy Garcia-Molina         13
Youssef Chahine             12
Martin Scorsese             12
Jay Chapman                 12
Name: count, dtype: int64

In [32]:
top_directors = netflix["director"].value_counts().head(10)

fig = px.bar(
    x=top_directors.index,
    y=top_directors.values,
    title="Top Netflix Directors"
)

fig.show(renderer="browser")

# Advanced Business Insights

1. Movies dominate Netflix's content library.

2. Netflix content production increased sharply after 2015.

3. Most movies fall within standard duration ranges.

4. Certain countries and directors dominate Netflix content creation.

5. Interactive analytics reveal strong global streaming trends.